import sqlite3 as sq

conn = sq.connect('storage.db')
curs = conn.cursor()
curs.execute('''CREATE TABLE TEAMS(
TEAMCODE TEXT(3) PRIMARY KEY,
TEAMNAME TEXT(50) NOT NULL)''')

curs.execute("INSERT INTO TEAMS(TEAMCODE, TEAMNAME) VALUES ('IND', 'India')")
curs.execute("INSERT INTO TEAMS(TEAMCODE, TEAMNAME) VALUES ('AUS', 'Australia')")
curs.execute("INSERT INTO TEAMS(TEAMCODE, TEAMNAME) VALUES ('ENG', 'England')")
curs.execute("INSERT INTO TEAMS(TEAMCODE, TEAMNAME) VALUES ('RSA', 'South Africa')")
curs.execute("INSERT INTO TEAMS(TEAMCODE, TEAMNAME) VALUES ('NZ', 'New Zealand')")

curs.execute('''CREATE TABLE PLAYERS(
PLAYERID INTEGER PRIMARY KEY,
PLAYERNAME TEXT(50) NOT NULL,
PLAYERTEAM TEXT(3) NOT NULL,
PLAYERROLE TEXT(3) NOT NULL,
PLAYERVALUE INTEGER NOT NULL)''')

curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (1, 'Virat Kohli', 'IND', 'BAT', 120)")#INDIA
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (2, 'Rohit Sharma', 'IND', 'BAT', 110)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (3, 'Mayank Agarwal', 'IND', 'BAT', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (4, 'Hardik Pandya', 'IND', 'AR', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (5, 'Kedar Jadhav', 'IND', 'AR', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (6, 'Ravindra Jadeja', 'IND', 'AR', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (7, 'Rishabh Pant', 'IND', 'WK', 60)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (8, 'Lokesh Rahul', 'IND', 'WK', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (9, 'MS Dhoni', 'IND', 'WK', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (10, 'Dinesh Karthik', 'IND', 'WK', 65)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (11, 'Kuldeep Yadav', 'IND', 'BWL', 75)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (12, 'Mohammed Shami', 'IND', 'BWL', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (13, 'Jasprit Bumrah', 'IND', 'BWL', 110)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (14, 'Bhuvneshwar Kumar', 'IND', 'BWL', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (15, 'Yuzvendra Chahal', 'IND', 'BWL', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (16, 'Aaron Finch', 'AUS', 'BAT', 100)")#AUSTRALIA
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (17, 'David Warner', 'AUS', 'BAT', 110)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (18, 'Steven Smith', 'AUS', 'BAT', 120)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (19, 'Glenn Maxwell', 'AUS', 'AR', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (20, 'Marcus Stoinis', 'AUS', 'AR', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (21, 'Matthew Wade', 'AUS', 'WK', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (22, 'Peter Handscomb', 'AUS', 'WK', 60)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (23, 'Alex Carey', 'AUS', 'WK', 65)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (24, 'Kane Richardson', 'AUS', 'BWL', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (25, 'Pat Cummins', 'AUS', 'BWL', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (26, 'Nathan Coulter-Nile', 'AUS', 'BWL', 95)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (27, 'Mitchell Starc', 'AUS', 'BWL', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (28, 'Jason Behrendroff', 'AUS', 'BWL', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (29, 'Adam Zampa', 'AUS', 'BWL', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (30, 'Nathan Lyon', 'AUS', 'BWL', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (31, 'Eoin Morgan', 'ENG', 'BAT', 100)")#ENGLAND
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (32, 'Jason Roy', 'ENG', 'BAT', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (33, 'Joe Root', 'ENG', 'BAT', 110)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (34, 'James Vince', 'ENG', 'BAT', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (35, 'Ben Stokes', 'ENG', 'AR', 110)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (36, 'Moeen Ali', 'ENG', 'AR', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (37, 'Chris Woakes', 'ENG', 'AR', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (38, 'Tom Curran', 'ENG', 'AR', 75)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (39, 'Liam Dawson', 'ENG', 'AR', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (40, 'Jofra Archer', 'ENG', 'AR', 95)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (41, 'Jonny Bairstow', 'ENG', 'WK', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (42, 'Jos Buttler', 'ENG', 'WK', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (43, 'Liam Plunkett', 'ENG', 'BWL', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (44, 'Adil Rashid', 'ENG', 'BWL', 75)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (45, 'Mark Wood', 'ENG', 'BWL', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (46, 'Faf Du Plessis', 'RSA', 'BAT', 110)")#SOUTH AFRICA
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (47, 'David Miller', 'RSA', 'BAT', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (48, 'Aiden Markram', 'RSA', 'BAT', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (49, 'Hashim Amla', 'RSA', 'BAT', 110)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (50, 'Rassie van der Dussen', 'RSA', 'BAT', 75)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (51, 'Jean-Paul Duminy', 'RSA', 'AR', 75)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (52, 'Andile Phehlukwayo', 'RSA', 'BWL', 65)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (53, 'Dwaine Pretorius', 'RSA', 'AR', 65)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (54, 'Chris Morris', 'RSA', 'AR', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (55, 'Quinton de Kock', 'RSA', 'WK', 95)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (56, 'Kagiso Rabada', 'RSA', 'BWL', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (57, 'Lungi Ngidi', 'RSA', 'BWL', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (58, 'Imran Tahir', 'RSA', 'BWL', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (59, 'Tabraiz Shamsi', 'RSA', 'BWL', 75)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (60, 'Beuran Hendricks', 'RSA', 'BWL', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (61, 'Kane Williamson', 'NZ', 'BAT', 120)")#NEW ZEALAND
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (62, 'Martin Guptill', 'NZ', 'BAT', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (63, 'Henry Nicholls', 'NZ', 'BAT', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (64, 'Ross Taylor', 'NZ', 'BAT', 100)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (65, 'Colin de Grandhomme', 'NZ', 'AR', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (66, 'Colin Munro', 'NZ', 'BAT', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (67, 'James Neesham', 'NZ', 'AR', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (68, 'Mitchell Santner', 'NZ', 'AR', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (69, 'Tom Blundell', 'NZ', 'WK', 70)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (70, 'Tom Latham', 'NZ', 'WK', 80)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (71, 'Trent Boult', 'NZ', 'BWL', 90)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (72, 'Lockie Ferguson', 'NZ', 'BWL', 95)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (73, 'Matt Henry', 'NZ', 'BWL', 85)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (74, 'Tim Southee', 'NZ', 'BWL', 95)")
curs.execute("INSERT INTO PLAYERS(PLAYERID, PLAYERNAME, PLAYERTEAM, PLAYERROLE, PLAYERVALUE) VALUES (75, 'Ish Sodhi', 'NZ', 'BWL', 75)")

curs.execute('''CREATE TABLE MATCHES(
MATCHNUMBER INTEGER PRIMARY KEY,
VERSUS TEXT(10) NOT NULL,
PLAYERIDS TEXT(200) NOT NULL,
SCORED TEXT(200) NOT NULL,
FACED TEXT(200) NOT NULL,
FOURS TEXT(200) NOT NULL,
SIXES TEXT(200) NOT NULL,
BOWLED TEXT(200) NOT NULL,
RUNSGIVEN TEXT(200) NOT NULL,
WICKETS TEXT(200) NOT NULL,
CATCHES TEXT(200) NOT NULL,
STUMPINGS TEXT(200) NOT NULL,
ROS TEXT(200) NOT NULL)''')

curs.execute("INSERT INTO MATCHES(MATCHNUMBER, VERSUS, PLAYERIDS, SCORED, FACED, FOURS, SIXES, BOWLED, RUNSGIVEN, WICKETS, CATCHES, STUMPINGS, ROS) VALUES (1, 'IND vs AUS', '[2, 3, 1, 4, 9, 8, 5, 14, 11, 15, 13, 17, 16, 18, 21, 19, 20, 23, 26, 25, 27, 29]', '[57, 117, 82, 48, 27, 11, 0, 0, 0, 0, 0, 56, 36, 69, 42, 28, 0, 55, 4, 8, 3, 1]', '[70, 109, 77, 27, 14, 3, 0, 0, 0, 0, 0, 84, 35, 70, 39, 14, 2, 35, 9, 7, 3, 3]', '[3, 16, 4, 4, 3, 1, 0, 0, 0, 0, 0, 5, 3, 5, 4, 5, 0, 5, 0, 1, 0, 0]', '[1, 0, 2, 3, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0]', '[0, 0, 0, 60, 0, 0, 6, 60, 54, 60, 60, 0, 0, 0, 0, 42, 42, 0, 60, 60, 60, 36]', '[0, 0, 0, 68, 0, 0, 14, 50, 55, 62, 61, 0, 0, 0, 0, 45, 62, 0, 63, 55, 74, 50]', '[0, 0, 0, 0, 0, 0, 0, 3, 0, 2, 3, 0, 0, 0, 0, 0, 2, 0, 1, 1, 1, 0]', '[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0]', '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]', '[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]')")
curs.execute("INSERT INTO MATCHES(MATCHNUMBER, VERSUS, PLAYERIDS, SCORED, FACED, FOURS, SIXES, BOWLED, RUNSGIVEN, WICKETS, CATCHES, STUMPINGS, ROS) VALUES (2, 'IND vs ENG', '[32, 41, 33, 31, 35, 42, 37, 43, 40, 44, 45, 8, 2, 1, 7, 4, 9, 5, 12, 11, 15, 13]', '[66, 111, 44, 1, 79, 20, 7, 1, 0, 0, 0, 0, 102, 66, 32, 45, 42, 12, 0, 0, 0, 0]', '[57, 109, 54, 9, 54, 8, 5, 4, 0, 0, 0, 9, 109, 76, 29, 33, 31, 13, 0, 0, 0, 0]', '[7, 10, 2, 0, 6, 1, 1, 0, 0, 0, 0, 0, 15, 7, 4, 4, 4, 1, 0, 0, 0, 0]', '[2, 6, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]', '[0, 0, 0, 0, 24, 0, 60, 60, 60, 36, 60, 0, 0, 0, 0, 60, 0, 0, 60, 60, 60, 60]', '[0, 0, 0, 0, 34, 0, 58, 55, 45, 40, 73, 0, 0, 0, 0, 60, 0, 0, 69, 72, 88, 44]', '[0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1, 0, 1]', '[0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0]', '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]', '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]')")
curs.execute("INSERT INTO MATCHES(MATCHNUMBER, VERSUS, PLAYERIDS, SCORED, FACED, FOURS, SIXES, BOWLED, RUNSGIVEN, WICKETS, CATCHES, STUMPINGS, ROS) VALUES (3, 'IND vs RSA', '[49, 55, 46, 50, 47, 51, 52, 54, 56, 58, 59, 3, 2, 1, 8, 9, 4, 5, 14, 11, 15, 13]', '[6, 10, 38, 22, 31, 3, 34, 42, 31, 0, 0, 8, 122, 18, 26, 34, 15, 0, 0, 0, 0, 0]', '[9, 17, 54, 37, 40, 11, 61, 34, 35, 2, 0, 12, 144, 34, 42, 46, 7, 0, 0, 0, 0, 0]', '[1, 1, 4, 1, 1, 0, 2, 1, 2, 0, 0, 1, 13, 1, 2, 2, 3, 0, 0, 0, 0, 0]', '[0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0]', '[0, 0, 0, 0, 0, 0, 51, 60, 60, 60, 54, 0, 0, 0, 0, 0, 36, 24, 60, 60, 60, 60]', '[0, 0, 0, 0, 0, 0, 40, 36, 39, 58, 54, 0, 0, 0, 0, 0, 31, 16, 44, 46, 51, 35]', '[0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 4, 2]', '[0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0]', '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]', '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]')")
curs.execute("INSERT INTO MATCHES(MATCHNUMBER, VERSUS, PLAYERIDS, SCORED, FACED, FOURS, SIXES, BOWLED, RUNSGIVEN, WICKETS, CATCHES, STUMPINGS, ROS) VALUES (4, 'IND vs NZ', '[62, 63, 61, 64, 67, 65, 70, 68, 73, 71, 72, 8, 2, 1, 7, 10, 4, 9, 6, 14, 15, 13]', '[1, 28, 67, 74, 12, 16, 10, 9, 1, 3, 0, 1, 1, 1, 32, 6, 32, 50, 77, 0, 5, 0]', '[14, 51, 95, 90, 18, 10, 11, 6, 2, 3, 0, 7, 4, 6, 56, 25, 62, 72, 59, 1, 5, 0]', '[0, 2, 6, 3, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 4, 1, 2, 1, 4, 0, 1, 0]', '[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0]', '[0, 0, 0, 0, 45, 12, 0, 60, 60, 60, 60, 0, 0, 0, 0, 0, 60, 0, 60, 60, 60, 60]', '[0, 0, 0, 0, 49, 13, 0, 34, 37, 42, 43, 0, 0, 0, 0, 0, 55, 0, 34, 43, 63, 39]', '[0, 0, 0, 0, 1, 0, 0, 2, 3, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 3, 1, 1]', '[0, 0, 2, 0, 1, 1, 3, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 2, 0, 0, 0]', '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]', '[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]')")

curs.execute('''CREATE TABLE USERSQUADS(
SQUADNAME TEXT(50) PRIMARY KEY,
MATCHNUMBER INTEGER NOT NULL, 
POINTSUSED INTEGER NOT NULL,
TEAMVALUE INTEGER NOT NULL,
PLAYERIDS TEXT(100) NOT NULL)''')

conn.commit()
